# These are supported funding model platforms

github: [jorgepassetti]
patreon: jorgepassetti
open_collective: jorgepassetti
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: jorgepassetti
otechie: # Replace with a single Otechie username
custom: ['https://www.buymeacoffee.com/jorgepassetti', 'https://www.paypal.me/jorgepassetti']
